routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('logout', function () {
    Session::flush();

    Auth::logout();

    return redirect()->route('login');
});

Route::get('/', function () {
    return view('auth.login');
})->name('login');

Auth::routes(['verify' => true]);

Route::get('password-reset', 'UserController@passwordReset')->name('reset-account-password');
Route::post('reset-password', 'UserController@resetPassword')->name('reset-password');
Route::get('welcome', function () {
    return view('welcome');
})->name('user-without-role');
Route::post('session/ajaxCheck','SessionController@ajaxCheck')->name('session.ajax.check');

Route::group(['middleware' => ['auth', 'verified', 'password', 'auth:role']], function () {
    
    Route::get('get-vat', 'PointOfSaleController@getVat');

    Route::get('/home', 'HomeController@index')->name('home');

    // POS
    Route::group(['middleware' => ['can:view-pos']], function () {
        Route::resource('point-of-sales', 'PointOfSaleController');
        Route::post('get-product', 'PointOfSaleController@getProduct');
        Route::post('create-customer', 'PointOfSaleController@createCustomer');

        Route::post('authorize-action', 'PointOfSaleController@authorizeAction');
        Route::post('hold-transaction', 'PointOfSaleController@holdTransaction');
        Route::get('get-held-sales', 'PointOfSaleController@getHeldSales');
        Route::post('delete-temp-sale', 'PointOfSaleController@destroy');
    });

    // Supplier
    Route::resource('suppliers', 'SupplierController');


    // Inventory Management
    Route::group(['middleware' => ['can:view-store']], function () {

        // inventory
        Route::resource('products', 'ProductController');

        Route::post('update-product-code/{product}', 'ProductController@updateProductCode')->name('update-product-code');
        
        Route::get("receive-products", "ReceiveProductController@index");
        Route::get("receive-products-data", "ReceiveProductController@create");
        Route::post("receive-products", "ReceiveProductController@store");
        
        Route::get('get-supplier-lpos/{supplier}', 'ReceiveProductController@getSupplierLpos');
        Route::get('get-lpo-items/{lpo}', 'ReceiveProductController@getLpoItems');
        Route::post('get-lpo-quantity-price', 'ReceiveProductController@getLpoQuantityAndPrice');
        
        // Product Categories
        Route::resource('product-categories', 'ProductCategoryController');
        // Unit of Measure
        Route::resource('unit-of-measures', 'UnitOfMeasureController');

    });
    // Customers
    Route::group(['middleware' => ['can:view-customers-management']], function () {
        Route::resource('customers', 'CustomerController');
        Route::post('update-customer-code/{customer}', 'CustomerController@updateCustomerCode')->name('update-customer-code');

        Route::resource('customer-vouchers', 'CustomerVoucherController');
        Route::post('create-customer-invoice', 'PointOfSaleController@createCustomerInvoice');

    });
    // CRM
    Route::group(['middleware' => ['can:view-crm']], function () {
        Route::resource('inquiry-types', 'InquiryTypeController');
        Route::resource('inquiry-statuses', 'InquiryStatusController');
    });

    // Bulk sms
    Route::group(['middleware' => ['can:view-bulk-sms']], function () {
        // Send Messages
        Route::resource('send-messages', 'SendMessageController');
        Route::get('get-contacts-groups', 'SendMessageController@getContactsGroups');

        //Fixed Schedule messages
        Route::resource('schedule-messages', 'MessageSchedulingController');
        Route::post('change-message-schedule-status/{id}', 'MessageSchedulingController@changeScheduleStatus');
        Route::get('get-message-schedule-data', 'MessageSchedulingController@getMessageScheduleData');
        Route::get('message-schedule-data/{id}', 'MessageSchedulingController@messageScheduleData');
        Route::resource('message-scheduling-phone-numbers', 'MessageSchedulePhoneNumberController');
        Route::get('get-message-schedule-contacts/{id}', 'MessageSchedulingController@getMessageSchedulecontacts');
        Route::post('add-contacts-to-schedule', 'MessageSchedulingController@addMessageSchedulecontacts');
        Route::post('detach-contacts-from-schedule', 'MessageSchedulingController@detachMessageScheduleContact');
        Route::get('get-message-schedule-groups/{id}', 'MessageSchedulingController@getMessageScheduleGroups');
        Route::post('add-groups-to-schedule', 'MessageSchedulingController@addMessageScheduleGroups');        
        Route::post('detach-group-from-schedule', 'MessageSchedulingController@detachMessageScheduleGroup');

        // Custom Schedule messages
        Route::resource('custom-message-schedules', 'CustomMessageScheduleController');
        Route::post('change-custom-message-schedule-status/{id}', 'CustomMessageScheduleController@changeCustomScheduleStatus');
        Route::resource('cms-phone-numbers', 'CustomMessageSchedulePhoneNumberController');
        Route::post('detach-custom-contacts-from-schedule', 'CustomMessageScheduleController@detachMessageScheduleContact');
        Route::get('custom-message-schedule-data/{id}', 'CustomMessageScheduleController@customMessageScheduleData');
        Route::post('detach-contacts-custom-schedule', 'CustomMessageScheduleController@detachMessageScheduleContact');
        Route::get('get-custom-schedule-contacts/{id}', 'CustomMessageScheduleController@getMessageSchedulecontacts');
        Route::post('add-custom-contacts-schedule', 'CustomMessageScheduleController@addMessageSchedulecontacts');
        Route::get('get-custom-schedule-groups/{id}', 'CustomMessageScheduleController@getMessageScheduleGroups');
        Route::post('detach-group-from-cms', 'CustomMessageScheduleController@detachMessageScheduleGroup');
        Route::post('add-groups-to-cms', 'CustomMessageScheduleController@addMessageScheduleGroups');    
                        

        // Contacts
        Route::resource('bulk-sms-contacts', 'ContactController');
        Route::post('update-contact', 'ContactController@update');        
        Route::post('update-contact-status/{id}', 'ContactController@updateContactStatus');        
        Route::post('import-contacts', 'ContactController@importContacts');
        //Get contacts (Vue)
        Route::get('get-contacts', 'ContactController@getContacts');
        Route::get('get-contacts/{id}', 'ContactController@getFilteredContacts');
        Route::post('send-message-contact', 'ContactController@sendMessage');        

        // groups
        Route::resource('groups', 'ContactGroupController');
        Route::get('get-group-contacts', 'ContactGroupController@getContacts');
        Route::get('groups/{id}', 'ContactGroupController@getFilteredGroups');
        Route::post('update-group-status/{id}', 'ContactGroupController@updateGroupStatus');
        Route::get('group-members/{id}', 'ContactGroupController@groupMembers');
        Route::post('add-group-members/{id}', 'ContactGroupController@addGroupMembers');
        Route::post('detach-contact', 'ContactGroupController@detachContact');
        Route::put('groups/{id}', 'ContactGroupController@update');
        Route::post('send-group-message', 'ContactGroupController@sendGroupMessage');  
        
        Route::get('get-group-members/{id}', 'ContactGroupController@getGroupMembers');      
        
    });

    // Procurement
    Route::group(['middleware' => ['can:view-procurement']], function () {
        Route::resource('local-purchase-orders', 'LocalPurchaseOrderController');
        Route::get('create-lpo-data', 'LocalPurchaseOrderController@getData');
        Route::resource('lpo-approvers', 'LocalPurchaseOrderApproverController');

        Route::get('get-lpo-data/{id}', 'LocalPurchaseOrderController@getLpoData');
        // LPO Items
        Route::resource('local-purchase-order-items', 'LocalPurchaseOrderItemController');
        Route::post('add-lpo-items', 'LocalPurchaseOrderItemController@addLpoItems');

        Route::get('get-lpo-approvers', 'LocalPurchaseOrderApproverController@getLpoApprovers');
        Route::put('update-lpo-approvers-sequence', 'LocalPurchaseOrderApproverController@updateApproversSequence');

        Route::get('get-lpo-status-logs/{id}', 'LocalPurchaseOrderController@statusLogs');
        Route::post('approve-lpo', 'LocalPurchaseOrderApproverController@approveLpo');
        Route::post('cancel-lpo-approval-request/{id}', 'LocalPurchaseOrderApproverController@cancelApprovalRequest');
        Route::post('send-lpo-approval-request/{id}', 'LocalPurchaseOrderApproverController@sendApprovalRequest');
        
        Route::resource('lpo-statuses', 'LocalPurchaseOrderStatusController');

        Route::resource('set-selling-price', 'SellingPriceController');

        //Download LPO
        Route::get('download-local-purchase-order/{lpo}', 'LocalPurchaseOrderController@downloadLPO')->name('download-local-purchase-order');


        // SRN
        Route::resource('store-requisition-notes', 'StoreRequisitionNoteController');
        Route::get('create-srn-data', 'StoreRequisitionNoteController@getData');
        Route::get('get-available-products/{id}', 'StoreRequisitionNoteController@getAvailableProducts');

        Route::get('get-srn-data/{id}', 'StoreRequisitionNoteController@getSrnData');
        Route::get('get-srn-status-logs/{id}', 'StoreRequisitionNoteController@statusLogs');

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable, SoftDeletes;

    protected $dates = ['deleted_at'];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'first_name', 
        'last_name', 
        'email', 
        'username', 
        'mobile', 
        'password', 
        'department_id',
        'supervisor_id',
        'status',
        'job_title',
        'avatar_url', 
        'avatar_img',
        'signature_url',
        'key_code',
        'signature'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * [getFullNameAttribute description]
     * @return [type] [string]
     */
    public function getFullNameAttribute()
    {
        return "{$this->first_name} {$this->last_name}";
    }
    
    
    public function getAvatarAttribute()
    {
        return "{$this->avatar_url}{$this->avatar_img}";
    }
   
    public function getUserSignatureAttribute()
    {
        return "{$this->signature_url}/{$this->signature}";
    }

    public function scopeActive($builder)
    {
        return $builder->where('status', true);
    }
    /**
     * [roles description]
     * @return [type] [description]
     */
    public function roles()
    {
        return $this->belongsToMany(
            Role::class,
            'role_user',
            'user_id',
            'role_id'
        );
    }

    /**
     * Checks if User has access to $permissions.
     */
    public function hasAccess(array $permissions) : bool
    {
        // check if the permission is available in any role
        foreach ($this->roles as $role) {
            if($role->hasAccess($permissions)) {
                return true;
            }
        }
        return false;
    }
    
    public function department()
    {
        return $this->belongsTo(Department::class, 'department_id', 'id');
    }

    public function supervisor()
    {     
        return $this->belongsTo(User::class, 'supervisor_id', 'id');   
    }

    public function scopeHasSignature($builder)
    {
        $check = $builder->where('id', auth()->user()->id)->pluck('signature')->first();
        
        if($check != null) return 1; 

        return 0;
    }
}

resources/views/layouts/common/navbar.blade.php
<div class="topbar-menu">
    <div class="container-fluid">
        <div id="navigation">
            <!-- Navigation Menu-->
            <ul class="navigation-menu">

                <li class="has-submenu">
                    <a href="javascript::void(0)"> <i class="mdi mdi-view-dashboard"></i>Dashboard</a>
                    <ul class="submenu">
                        <li><a href="{{ route('home') }}">Sales Dashboard</a></li>
                        <li><a href="javascript::void(0)">Analytics Dashboard</a></li>
                        <li><a href="javascript::void(0)">CRM Dashboard</a></li>
                    </ul>
                </li>


                @can('view-pos')
                    <li class="has-submenu">
                        <a href="{{ url('point-of-sales') }}">
                            <i class="mdi mdi-basket"></i>POS
                        </a>
                    </li>
                @endcan
                
                @can('view-store')
                    <li class="has-submenu">
                        <a href="javascript::void(0)">
                            <i class="mdi mdi-store"></i>Inventory Mngmt
                        </a>
                        <ul class="submenu">
                            @can('register-products')
                                <li><a href="{{ route('products.create') }}">Register Products</a></li>
                            @endcan

                            @can('view-products')
                                <li><a href="{{ url('products') }}">View Products</a></li>
                            @endcan

                            @can('view-products-categories')
                                <li><a href="{{ url('product-categories') }}">Product Categories</a></li>
                            @endcan

                            @can('view-unit-of-measure')
                                <li><a href="{{ url('unit-of-measures') }}">Unit of Measures</a></li>
                            @endcan
                            
                            @can('receive-products')
                                <li><a href="{{ url('receive-products') }}">Receive Products</a></li>
                            @endcan
                        </ul>
                    </li>
                @endcan

                @can('view-bulk-sms')
                    <li class="has-submenu">
                        <a href="javascript::void(0)">
                            <i class="mdi mdi-message-text"></i>Bulk SMS
                        </a>
                        <ul class="submenu">
                            @can('send-messages')<li><a href="{{ url('send-messages') }}">Send Message</a></li>@endcan
                            @can('schedule-messages')<li><a href="{{ url('schedule-messages') }}">Schedule Messages</a></li>@endcan
                            <li><a href="{{ url('bulk-sms-contacts') }}">Contacts</a></li>
                        </ul>
                    </li>
                @endcan

                @can('view-suppliers-management')
                    <li class="has-submenu">
                        <a href="javascript::void(0);">
                            <i class="mdi mdi-truck-delivery"></i>Supplier Mngmt
                        </a>
                        <ul class="submenu">
                            @can('create-suppliers')
                                <li><a href="{{ route('suppliers.create') }}">Create Suppliers</a></li>                                
                            @endcan

                            @can('view-suppliers')
                                <li><a href="{{ url('suppliers') }}">View Suppliers</a></li>                                
                            @endcan
                            <li><a href="javascript::void(0)">Supplier Statememts</a></li>
                        </ul>
                    </li>
                @endcan

                @can('view-customers-management')
                    <li class="has-submenu">
                        <a href="javascript::void(0)"> <i class="mdi mdi-account-card-details"></i>Customer Mngmt</a>
                        <ul class="submenu">
                            @can('create-customers')
                                <li><a href="{{ route('customers.create') }}">Create Customer</a></li>
                            @endcan

                            @can('view-customers')
                                <li><a href="{{ url('customers') }}">View Customers</a></li>
                            @endcan
                            <li><a href="javascript::void(0)">Customers Loyalty</a></li>
                            <li><a href="{{ url('customer-vouchers') }}">Customers Vouchers</a></li>
                        </ul>
                    </li>
                @endcan
                
                @can('view-accounts')
                    <li class="has-submenu">
                        <a href="javascript::void(0)"> <i class="mdi mdi-bank"></i>Accounts </a>
                        <ul class="submenu megamenu">
                            <li>
                                <ul>
                                    <li><a href="{{ url('invoices') }}">Invoices</a></li>
                                    <li><a href="javascript::void(0)">Petty Cash</a></li>
                                    <li><a href="javascript::void(0)">Cash Flow Statememt</a></li>
                                    <li><a href="javascript::void(0)">Income Statement</a></li>
                                </ul>
                            </li>
                            <li>
                                <ul>
                                    <li><a href="javascript::void(0)">Bank Statement</a></li>
                                    <li><a href="javascript::void(0)">Bank Reconcilation</a></li>
                                    <li><a href="javascript::void(0)">Balance Sheet</a></li>
                                    @can('view-charts-of-account')<li><a href="{{ url('chart-of-accounts') }}">Charts of Account</a></li>@endcan
                                </ul>
                            </li>
                        </ul>
                    </li>
                @endcan

                @can('view-procurement')
                    <li class="has-submenu">
                        <a href="javascript::void(0)"> <i class="mdi mdi-forklift"></i>Procurement
                        </a>
                        <ul class="submenu">
                            @can('view-lpos')<li><a href="{{ url('local-purchase-orders') }}">Local Purchase Orders</a></li>@endcan
                            @can('view-srns')<li><a href="{{ url('store-requisition-notes') }}">Store Requisition Notes</a></li>@endcan
                            <li><a href="{{ url('good-issue-notes') }}">Good Issue Note</a></li>
                        </ul>
                    </li>
                @endcan

                @can('view-settings')
                    <li class="has-submenu">
                        <a href="javascript::void(0)"> <i class="mdi mdi-settings"></i>Settings</a>
                        <ul class="submenu megamenu">
                            <li>
                                <ul>
                                    @can('view-users')<li><a href="{{ url('users') }}">Users Management</a></li>@endcan
                                    @can('view-roles')<li><a href="{{ url('roles') }}">Roles Management</a></li>@endcan
                                    @can('view-departments')<li><a href="{{ url('departments') }}">Departments</a></li>@endcan
                                </ul>
                            </li>
                            <li>
                                <ul>
                                    <li><a href="{{ url('system-settings') }}">System Settings</a></li>
                                    <li><a href="javascript::void(0)">System Backup</a></li>
                                    <li><a href="{{ url('my-account') }}">My Account</a></li>
                                </ul>
                            </li>
                        </ul>
                    </li>
                @endcan
            </ul>
            <!-- End navigation menu -->

            <div class="clearfix"></div>
        </div>
        <!-- end #navigation -->
    </div>
    <!-- end container -->
</div>
<!-- end navbar-custom -->

resources/views/layouts/common/scripts.blade.php
<script src="{{ asset('js/app.js') }}"></script>
<!-- Vendor js -->
<script src="{{ asset('assets/js/vendor.min.js') }}"></script>

<!-- App js -->
<script src="{{ asset('assets/js/app.min.js') }}"></script>
<!-- Datatable plugin js -->
<script src="{{ asset('assets/libs/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('assets/libs/datatables/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ asset('assets/libs/datatables/dataTables.responsive.min.js') }}"></script>
<script src="{{ asset('assets/libs/datatables/responsive.bootstrap4.min.js') }}"></script>
<script src="{{ asset('assets/libs/datatables/dataTables.buttons.min.js') }}"></script>
<script src="{{ asset('assets/libs/datatables/buttons.bootstrap4.min.js') }}"></script>
<script src="{{ asset('assets/libs/datatables/buttons.html5.min.js') }}"></script>
<script src="{{ asset('assets/libs/datatables/buttons.print.min.js') }}"></script>
<script src="{{ asset('assets/libs/datatables/dataTables.keyTable.min.js') }}"></script>
<script src="{{ asset('assets/libs/datatables/dataTables.fixedHeader.min.js') }}"></script>
<script src="{{ asset('assets/libs/datatables/dataTables.scroller.min.js') }}"></script>
<script src="{{ asset('assets/libs/jszip/jszip.min.js') }}"></script>
<script src="{{ asset('assets/libs/pdfmake/pdfmake.min.js') }}"></script>
<script src="{{ asset('assets/libs/pdfmake/vfs_fonts.js') }}"></script>
<!-- Toastr js -->
<script src="{{ asset('assets/libs/toastr/toastr.min.js') }}"></script>
<script src="{{ asset('assets/libs/sweetalert2/sweetalert2.min.js') }}"></script>
<script src="{{ asset('assets/libs/dropify/dropify.min.js') }}"></script>
<script src="{{ asset('assets/libs/select2/dist/js/select2.full.min.js') }}"></script>
<script src="{{ asset('assets/libs/tooltipster/tooltipster.bundle.min.js') }}"></script>
<script src="{{ asset('assets/libs/bootstrap-maxlength/bootstrap-maxlength.min.js') }}"></script>

<script src="{{ asset('assets/libs/bootstrap-tagsinput/bootstrap-tagsinput.min.js') }}"></script>
{{-- Am Charts --}}
<script src="{{ asset('assets/libs/amcharts4/core.js') }}"></script>
<script src="{{ asset('assets/libs/amcharts4/charts.js') }}"></script>
<script src="{{ asset('assets/libs/amcharts4/themes/material.js') }}"></script>
<script src="{{ asset('assets/libs/amcharts4/themes/animated.js') }}"></script>
<script src="{{ asset('assets/libs/amcharts4/themes/dataviz.js') }}"></script>


<script src="{{  asset('assets/libs/bootstrap-touchspin/jquery.bootstrap-touchspin.min.js') }}"></script>

@if(session('success'))
<script type="text/javascript">
    $(document).ready(function(){
        var message = {!! json_encode(session('success')) !!};
        toastr.success(message, "Success!", {   
            "closeButton": true,        
            "progressBar": true,
            "onclick": null,
            "positionClass": "toast-top-right",
            "showDuration": "500",
            "hideDuration": "2000",
            "timeOut": "8000",
            "extendedTimeOut": "2000",
            "showEasing": "swing",
            "hideEasing": "linear",
            "showMethod": "fadeIn",
            "hideMethod": "fadeOut"
        });
    });             
</script>
@elseif(session('error'))
<script type="text/javascript">
    $(document).ready(function(){
        var message = {!! json_encode(session('error')) !!};
        toastr.warning(message, "Warning!", {
            "closeButton": true,
            "progressBar": true,
            "onclick": null,
            "showDuration": "500",
            "hideDuration": "2000",
            "timeOut": "8000",
            "extendedTimeOut": "2000",
            "positionClass": "toast-top-right",
            "showEasing": "swing",
            "hideEasing": "linear",
            "showMethod": "fadeIn",
            "hideMethod": "fadeOut"
        });
    });             
</script>
@elseif(session('danger'))
<script type="text/javascript">
    $(document).ready(function(){
        var message = {!! json_encode(session('danger')) !!};
        toastr.error(message, "Error.", {
            "closeButton": true,
            "progressBar": true,
            "onclick": null,
            "showDuration": "500",
            "hideDuration": "2000",
            "positionClass": "toast-top-right",
            "timeOut": "8000",
            "extendedTimeOut": "2000",
            "showEasing": "swing",
            "hideEasing": "linear",
            "showMethod": "fadeIn",
            "hideMethod": "fadeOut"
        });
    });             
</script>
@endif

<script>

    // (".tooltip-hover").tooltipster();

	$(document).ready(function() {
        $(".datatables_responsive").DataTable({
            "pagingType": "full_numbers"
        });


        $("input[name='demo3_21']").TouchSpin({initval:40})

        $(".select2").select2({
            width: '100%',
            theme: 'classic'
        });

        $("textarea#textarea").maxlength({
            alwaysShow:!0,
            warningClass:"badge badge-success",
            limitReachedClass:"badge badge-danger"
        });

    });

    $('#myTab a').click(function(e) {
        e.preventDefault();
        $(this).tab('show');
    });

    // store the currently selected tab in the hash value
    $("ul.nav-tabs > li > a").on("shown.bs.tab", function(e) {
        var id = $(e.target).attr("href").substr(1);
        window.location.hash = id;
    });

    // on load of the page: switch to the currently selected tab
    var hash = window.location.hash;
    $('#myTab a[href="' + hash + '"]').tab('show');

    $(".dropify").dropify({
        messages:{
            default:"Drag and drop a file here or click",
            replace:"Drag and drop or click to replace",
            remove:"Remove",
            error:"Ooops, something wrong appended."
        },
        error:{
            fileSize:"The file size is too big (1M max)."
        }
    });

    $('.delete').on('click', function(e) {
        e.preventDefault();
        var form = $(this).parents('form');
        Swal.fire({
            title: 'Are you sure?',
            text: "You won't be able to revert this action!",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Yes, delete it!'
        }).then((result) => {
            if (result.value) {
                form.submit()   
            }
        })
    });
</script>

resources/views/layouts/common/topbar.blade.php
<!-- Topbar Start -->
<div class="navbar-custom">
    <div class="container-fluid">
        <ul class="list-unstyled topnav-menu float-right mb-0">

            <li class="dropdown notification-list">
                <!-- Mobile menu toggle-->
                <a class="navbar-toggle nav-link">
                    <div class="lines">
                        <span></span>
                        <span></span>
                        <span></span>
                    </div>
                </a>
                <!-- End mobile menu toggle-->
            </li>

            <li class="dropdown notification-list">
                <a class="nav-link dropdown-toggle nav-user mr-0 waves-effect waves-light" href="{{ url('my-account') }}" role="button" aria-haspopup="false" aria-expanded="false">
                    <img src="{{ auth()->user()->avatar }}" alt="user-image" class="rounded-circle">
                    {{ auth()->user()->full_name }}
                </a>
            </li>

            <li class="dropdown notification-list">
                <!-- item-->
                <a class="nav-link dropdown-toggle nav-user mr-0 waves-effect waves-light" href="{{ route('logout') }}" onclick="event.preventDefault();
                document.getElementById('logout-form').submit();">
                    <i class="mdi mdi-logout-variant"></i>
                    <span>Logout</span>
                </a>
                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                    @csrf
                </form>

            </li>

        </ul>

        <!-- LOGO -->
        <div class="logo-box">
            <a href="{{ url('/home') }}" class="logo text-center">
                <span class="logo-lg">
                    <img src="{{ asset('assets/images/carrymore_logo.png') }}" alt="" height="60">
                    <!-- <span class="logo-lg-text-light">Zircos</span> -->
                </span>
                <span class="logo-sm">
                    <!-- <span class="logo-sm-text-dark">Z</span> -->
                    <img src="{{ asset('assets/images/carrymore_logo.png') }}" alt="" height="60">
                </span>
            </a>
        </div>


        <ul class="list-unstyled topnav-menu topnav-menu-left m-0">

            <li class="d-none d-sm-block">
                <form class="app-search">
                    <div class="app-search-box">
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Search...">
                            <div class="input-group-append">
                                <button class="btn" type="submit">
                                    <i class="fas fa-search"></i>
                                </button>
                            </div>
                        </div>
                    </div>
                </form>
            </li>
        </ul>
        <div class="clearfix"></div>
    </div>
</div>
<!-- end Topbar -->