routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('logout', function () {
    Session::flush();

    Auth::logout();

    return redirect()->route('login');
});

Route::get('/', function () {
    return view('auth.login');
})->name('login');

Auth::routes(['verify' => true]);

Route::get('password-reset', 'UserController@passwordReset')->name('reset-account-password');
Route::post('reset-password', 'UserController@resetPassword')->name('reset-password');
Route::get('welcome', function () {
    return view('welcome');
})->name('user-without-role');
Route::post('session/ajaxCheck','SessionController@ajaxCheck')->name('session.ajax.check');

Route::group(['middleware' => ['auth', 'verified', 'password', 'auth:role']], function () {
    
    Route::get('get-vat', 'PointOfSaleController@getVat');

    Route::get('/home', 'HomeController@index')->name('home');

    // POS
    Route::group(['middleware' => ['can:view-pos']], function () {
        Route::resource('point-of-sales', 'PointOfSaleController');
        Route::post('get-product', 'PointOfSaleController@getProduct');
        Route::post('create-customer', 'PointOfSaleController@createCustomer');

        Route::post('authorize-action', 'PointOfSaleController@authorizeAction');
        Route::post('hold-transaction', 'PointOfSaleController@holdTransaction');
        Route::get('get-held-sales', 'PointOfSaleController@getHeldSales');
        Route::post('delete-temp-sale', 'PointOfSaleController@destroy');
    });

    // Supplier
    Route::resource('suppliers', 'SupplierController');


    // Inventory Management
    Route::group(['middleware' => ['can:view-store']], function () {

        // inventory
        Route::resource('products', 'ProductController');

        Route::post('update-product-code/{product}', 'ProductController@updateProductCode')->name('update-product-code');
        
        Route::get("receive-products", "ReceiveProductController@index");
        Route::get("receive-products-data", "ReceiveProductController@create");
        Route::post("receive-products", "ReceiveProductController@store");
        
        Route::get('get-supplier-lpos/{supplier}', 'ReceiveProductController@getSupplierLpos');
        Route::get('get-lpo-items/{lpo}', 'ReceiveProductController@getLpoItems');
        Route::post('get-lpo-quantity-price', 'ReceiveProductController@getLpoQuantityAndPrice');
        
        // Product Categories
        Route::resource('product-categories', 'ProductCategoryController');
        // Unit of Measure
        Route::resource('unit-of-measures', 'UnitOfMeasureController');

    });
    // Customers
    Route::group(['middleware' => ['can:view-customers-management']], function () {
        Route::resource('customers', 'CustomerController');
        Route::post('update-customer-code/{customer}', 'CustomerController@updateCustomerCode')->name('update-customer-code');

        Route::resource('customer-vouchers', 'CustomerVoucherController');
        Route::post('create-customer-invoice', 'PointOfSaleController@createCustomerInvoice');

    });
    // CRM
    Route::group(['middleware' => ['can:view-crm']], function () {
        Route::resource('inquiry-types', 'InquiryTypeController');
        Route::resource('inquiry-statuses', 'InquiryStatusController');
    });

    // Bulk sms
    Route::group(['middleware' => ['can:view-bulk-sms']], function () {
        // Send Messages
        Route::resource('send-messages', 'SendMessageController');
        Route::get('get-contacts-groups', 'SendMessageController@getContactsGroups');

        //Fixed Schedule messages
        Route::resource('schedule-messages', 'MessageSchedulingController');
        Route::post('change-message-schedule-status/{id}', 'MessageSchedulingController@changeScheduleStatus');
        Route::get('get-message-schedule-data', 'MessageSchedulingController@getMessageScheduleData');
        Route::get('message-schedule-data/{id}', 'MessageSchedulingController@messageScheduleData');
        Route::resource('message-scheduling-phone-numbers', 'MessageSchedulePhoneNumberController');
        Route::get('get-message-schedule-contacts/{id}', 'MessageSchedulingController@getMessageSchedulecontacts');
        Route::post('add-contacts-to-schedule', 'MessageSchedulingController@addMessageSchedulecontacts');
        Route::post('detach-contacts-from-schedule', 'MessageSchedulingController@detachMessageScheduleContact');
        Route::get('get-message-schedule-groups/{id}', 'MessageSchedulingController@getMessageScheduleGroups');
        Route::post('add-groups-to-schedule', 'MessageSchedulingController@addMessageScheduleGroups');        
        Route::post('detach-group-from-schedule', 'MessageSchedulingController@detachMessageScheduleGroup');

        // Custom Schedule messages
        Route::resource('custom-message-schedules', 'CustomMessageScheduleController');
        Route::post('change-custom-message-schedule-status/{id}', 'CustomMessageScheduleController@changeCustomScheduleStatus');
        Route::resource('cms-phone-numbers', 'CustomMessageSchedulePhoneNumberController');
        Route::post('detach-custom-contacts-from-schedule', 'CustomMessageScheduleController@detachMessageScheduleContact');
        Route::get('custom-message-schedule-data/{id}', 'CustomMessageScheduleController@customMessageScheduleData');
        Route::post('detach-contacts-custom-schedule', 'CustomMessageScheduleController@detachMessageScheduleContact');
        Route::get('get-custom-schedule-contacts/{id}', 'CustomMessageScheduleController@getMessageSchedulecontacts');
        Route::post('add-custom-contacts-schedule', 'CustomMessageScheduleController@addMessageSchedulecontacts');
        Route::get('get-custom-schedule-groups/{id}', 'CustomMessageScheduleController@getMessageScheduleGroups');
        Route::post('detach-group-from-cms', 'CustomMessageScheduleController@detachMessageScheduleGroup');
        Route::post('add-groups-to-cms', 'CustomMessageScheduleController@addMessageScheduleGroups');    
                        

        // Contacts
        Route::resource('bulk-sms-contacts', 'ContactController');
        Route::post('update-contact', 'ContactController@update');        
        Route::post('update-contact-status/{id}', 'ContactController@updateContactStatus');        
        Route::post('import-contacts', 'ContactController@importContacts');
        //Get contacts (Vue)
        Route::get('get-contacts', 'ContactController@getContacts');
        Route::get('get-contacts/{id}', 'ContactController@getFilteredContacts');
        Route::post('send-message-contact', 'ContactController@sendMessage');        

        // groups
        Route::resource('groups', 'ContactGroupController');
        Route::get('get-group-contacts', 'ContactGroupController@getContacts');
        Route::get('groups/{id}', 'ContactGroupController@getFilteredGroups');
        Route::post('update-group-status/{id}', 'ContactGroupController@updateGroupStatus');
        Route::get('group-members/{id}', 'ContactGroupController@groupMembers');
        Route::post('add-group-members/{id}', 'ContactGroupController@addGroupMembers');
        Route::post('detach-contact', 'ContactGroupController@detachContact');
        Route::put('groups/{id}', 'ContactGroupController@update');
        Route::post('send-group-message', 'ContactGroupController@sendGroupMessage');  
        
        Route::get('get-group-members/{id}', 'ContactGroupController@getGroupMembers');      
        
    });

    // Procurement
    Route::group(['middleware' => ['can:view-procurement']], function () {
        Route::resource('local-purchase-orders', 'LocalPurchaseOrderController');
        Route::get('create-lpo-data', 'LocalPurchaseOrderController@getData');
        Route::resource('lpo-approvers', 'LocalPurchaseOrderApproverController');

        Route::get('get-lpo-data/{id}', 'LocalPurchaseOrderController@getLpoData');
        // LPO Items
        Route::resource('local-purchase-order-items', 'LocalPurchaseOrderItemController');
        Route::post('add-lpo-items', 'LocalPurchaseOrderItemController@addLpoItems');

        Route::get('get-lpo-approvers', 'LocalPurchaseOrderApproverController@getLpoApprovers');
        Route::put('update-lpo-approvers-sequence', 'LocalPurchaseOrderApproverController@updateApproversSequence');

        Route::get('get-lpo-status-logs/{id}', 'LocalPurchaseOrderController@statusLogs');
        Route::post('approve-lpo', 'LocalPurchaseOrderApproverController@approveLpo');
        Route::post('cancel-lpo-approval-request/{id}', 'LocalPurchaseOrderApproverController@cancelApprovalRequest');
        Route::post('send-lpo-approval-request/{id}', 'LocalPurchaseOrderApproverController@sendApprovalRequest');
        
        Route::resource('lpo-statuses', 'LocalPurchaseOrderStatusController');

        Route::resource('set-selling-price', 'SellingPriceController');

        //Download LPO
        Route::get('download-local-purchase-order/{lpo}', 'LocalPurchaseOrderController@downloadLPO')->name('download-local-purchase-order');


        // SRN
        Route::resource('store-requisition-notes', 'StoreRequisitionNoteController');
        Route::get('create-srn-data', 'StoreRequisitionNoteController@getData');
        Route::get('get-available-products/{id}', 'StoreRequisitionNoteController@getAvailableProducts');

        Route::get('get-srn-data/{id}', 'StoreRequisitionNoteController@getSrnData');
        Route::get('get-srn-status-logs/{id}', 'StoreRequisitionNoteController@statusLogs');

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable, SoftDeletes;

    protected $dates = ['deleted_at'];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'first_name', 
        'last_name', 
        'email', 
        'username', 
        'mobile', 
        'password', 
        'department_id',
        'supervisor_id',
        'status',
        'job_title',
        'avatar_url', 
        'avatar_img',
        'signature_url',
        'key_code',
        'signature'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * [getFullNameAttribute description]
     * @return [type] [string]
     */
    public function getFullNameAttribute()
    {
        return "{$this->first_name} {$this->last_name}";
    }
    
    
    public function getAvatarAttribute()
    {
        return "{$this->avatar_url}{$this->avatar_img}";
    }
   
    public function getUserSignatureAttribute()
    {
        return "{$this->signature_url}/{$this->signature}";
    }

    public function scopeActive($builder)
    {
        return $builder->where('status', true);
    }
    /**
     * [roles description]
     * @return [type] [description]
     */
    public function roles()
    {
        return $this->belongsToMany(
            Role::class,
            'role_user',
            'user_id',
            'role_id'
        );
    }

    /**
     * Checks if User has access to $permissions.
     */
    public function hasAccess(array $permissions) : bool
    {
        // check if the permission is available in any role
        foreach ($this->roles as $role) {
            if($role->hasAccess($permissions)) {
                return true;
            }
        }
        return false;
    }
    
    public function department()
    {
        return $this->belongsTo(Department::class, 'department_id', 'id');
    }

    public function supervisor()
    {     
        return $this->belongsTo(User::class, 'supervisor_id', 'id');   
    }

    public function scopeHasSignature($builder)
    {
        $check = $builder->where('id', auth()->user()->id)->pluck('signature')->first();
        
        if($check != null) return 1; 

        return 0;
    }
}

resources/views/gin/ginpdf.blade.php
<!DOCTYPE html>

<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{{ public_path('assets/css/bootstrap.min.css') }}">
    <title>Store Requisition Note ({{ $data->srn->number }}) Good Issue Note</title>

    <style>
        @page{
            margin-top: 70px;
        }
        body {
            font-family: "Cambria";
            font-size: 14px;
            background-color: white;
            color: black
        }
        .logo {
            width: 250px;
            max-width: 50%;
            height: 70px;
            float: left;
        }

        .signature {
            width: 100px;
            height: 50px;
        }

        table, tr, td {
            padding: 0px;
            color: black
        }
        .header{
            height: 80px;
        }
        .lpo_number{
            float: right;
            margin-top: 10px;
        }
        .supplier .vendor{
            margin-bottom: 10px;
        }
        .supplier .details {
            width: 100%;
            margin-left: 10px;
        }
        .info{
            margin-top: 5px;
        }
        
        .page_break { page-break-before: always; }
        .no_page_break { page-break-before: avoid; }
        hr{
            color: grey;
            border-bottom: 1px solid grey;
        }
    </style>
</head>
        
    <div class="header">
        <div class="logo">
            <img src="{{ public_path('storage/logo/carrymore_logo.png') }}" height="100%" width="100%">
        </div>
        <div class="lpo_number">
            <p>
                SRN Number:<strong> {{ $data->srn->number }} </strong><br>
                GIN Date: <strong>{{ date('d-m-Y H:i A', strtotime($data->created_at)) }}</strong>
            </p>
        </div>
    </div>
    <hr>
    <div class="row supplier">
        <div class="details">
            <div class="vendor">Items Issued To:</div>
            <div class="address">
                <address>
                    <strong>{{ $data->srn->user->full_name }}</strong><br>
                    {{ $data->srn->user->department->name }}<br>
                    <abbr title="Phone">Phone:</abbr> {{ $data->srn->user->mobile }}<br>
                    <abbr title="Phone">Email:</abbr> {{ $data->srn->user->email }}
                </address>
            </div>
        </div>
    </div>
    <!-- end row -->

    <div class="info">
        <p>Following approval of Store Requisition Note - {{ $data->srn->number }}, the following items have been issued to you ({{ $data->user->full_name }})</p>
    </div>

    <div>
        <table class="table table-bordered table-condensed table-striped" width="100%">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Item</th>
                    <th>Quantity</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($data->srn->items as $key => $item)
                    <tr>
                        <td>{{ $key+1 }}</td>
                        <td>{{ $item->product->name }}</td>
                        <td>{{ number_format($item->quantity).' '.$item->product->unitOfMeasure->name }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    <div style="page-break-inside: avoid">

        <div style="margin-top: 15px;">
            Note: <br>
            I confirm that all goods above have been received and that are in good order and condition.<br>
            <table width="100%">
                <tr>
                    <td width="15%"><b>Full Name:</b></td>
                    <td style="border-bottom: 0.5px solid #000">{{ $data->srn->user->full_name }}</td>
                    <td width="8%"><b>Sign:</b></td>
                    <td width="20%" style="border-bottom: 0.5px solid #000" width="20%"><img class="signature" src="{{ public_path('storage/signatures/'.$data->user->signature) }}" height="100%" width="100%"></td>
                    <td width="8%"><b>Date:</b></td>
                    <td style="border-bottom: 0.5px solid #000" width="20%">{{ date('d/m/Y', strtotime($data->created_at)) }}</td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                </tr>                
                
            </table>
        </div>
        
    </div>     

resources/views/gin/index.blade.php
@extends('layouts.app', ['title' => 'GIN'])

@section('content')

     <!-- start page title -->
     <div class="row">
        <div class="col-12">
            <div class="page-title-box">
                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="{{ url('/home') }}">Home</a></li>
                        <li class="breadcrumb-item"><a href="javascript: void(0);">Procurement</a></li>
                        <li class="breadcrumb-item active">GIN</li>
                    </ol>
                </div>
                <h4 class="page-title">Good Issue Notes</h4>
            </div>
        </div>
    </div>
    <!-- end page title -->

    <div class="row">
        <div class="col-sm-12">
            <div class="card-box">

                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <table class="table table-striped table-bordered dt-responsive nowrap datatables_responsive" style="border-collapse: collapse; border-spacing: 0; width: 100%;">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>SRN No</th>
                            <th>Requested By</th>
                            <th>Status</th>
                            <th>Comment</th>
                            <th>Date Created</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($gins as $key => $gin)
                            <tr>
                                <td>{{ $key + 1 }}</td>
                                <td><a href="{{ route('store-requisition-notes.show', [$gin->srn]) }}"><code>{{ $gin->srn->number }}</code></a></td>
                                <td>{{ $gin->srn->user->full_name }}</td>
                                <td>
                                    @if ($gin->consent == null && $gin->user_id == auth()->user()->id)
                                        <span data-toggle="modal" data-target="#view-gin-status-{{ $gin->id }}" class="btn btn-info btn-rounded btn-xs" style="border-radius:15px;cursor:pointer">Pending</span>   
                                    @else
                                        @if ($gin->consent)
                                            <span class="btn btn-success btn-rounded btn-xs">Accepted</span>
                                        @else
                                            <span class="btn btn-danger btn-rounded btn-xs">Rejected</span>                                            
                                        @endif
                                    @endif
                                    <div class="modal fade" id="view-gin-status-{{ $gin->id }}" tabindex="-1"  data-backdrop="static" role="dialog" style="margin-top: 50px">
                                        <div class="modal-dialog modal-lg" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h4 class="modal-title" align="center">{{ $gin->srn->number }} Good Issue Note Consent</h4>
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                        <span aria-hidden="true">&times;</span>
                                                    </button>
                                                </div>
                                                <form action="{{ url('good-issue-notes', ['id' => $gin->id]) }}" method="POST">
                                                    @csrf
                                                    @method('PUT')
                                                    <div class="modal-body">
                                                        <div class="row form-group">                                                                 
                                                            <label class="col-6">
                                                                <input type="radio" class="option-input radio" name="consent" value="true"/>
                                                                <span style="color:green">Accept GIN</span>
                                                            </label>
                                                            <label class="col-6">
                                                                <input type="radio" class="option-input-reject radio" name="consent" value="false"/>
                                                                <span style="color:red">Reject GIN</span>
                                                            </label>
                                                        </div>
                                                        <div class="row form-group">
                                                            <div class="col-12">
                                                                <textarea name="comment" rows="3" class="form-control" placeholder="Reason for rejecting GIN"></textarea>
                                                            </div>
                                                        </div>
                                                        
                                                    </div>
                                                    <div class="modal-footer">
                                                        <button type="button" class="btn btn-dark waves-effect " data-dismiss="modal">Close</button>
                                                        <button type="submit" class="btn btn-info waves-effect">Acknowledge Consent</button>
                                                    </div>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </td>
                                <td>
                                    @if ($gin->comment == null)
                                        <code>N/A</code>
                                    @else
                                        {{ $gin->comment }}
                                    @endif
                                </td>
                                <td>{{ date('d-m-Y H:i A', strtotime($gin->created_at)) }}</td>
                                <td>
                                    @if ($gin->consent != null && $gin->consent)
                                        <a href="{{ route('download-good-issue-note', [$gin]) }}" class="btn btn-xs btn-primary"><i class="mdi mdi-download"></i> Download GIN</a>            
                                    @else
                                        <button class="btn btn-xs btn-orange" data-toggle="popover" data-placement="bottom" data-trigger="focus" data-content="You are not permitted to downlaod GIN if it has not been accepted" data-original-title="GIN Not Accepted"><i class="mdi mdi-download-off"></i> Download GIN</button>
                                    @endif
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>

@endsection