routes/web.php
        Route::resource('customer-vouchers', 'CustomerVoucherController');
        Route::post('create-customer-invoice', 'PointOfSaleController@createCustomerInvoice');

    });
    // CRM
    Route::group(['middleware' => ['can:view-crm']], function () {
        Route::resource('inquiry-types', 'InquiryTypeController');
        Route::resource('inquiry-statuses', 'InquiryStatusController');
    });

    // Bulk sms
    Route::group(['middleware' => ['can:view-bulk-sms']], function () {
        // Send Messages
        Route::resource('send-messages', 'SendMessageController');
        Route::get('get-contacts-groups', 'SendMessageController@getContactsGroups');

        //Fixed Schedule messages
        Route::resource('schedule-messages', 'MessageSchedulingController');
        Route::post('change-message-schedule-status/{id}', 'MessageSchedulingController@changeScheduleStatus');
        Route::get('get-message-schedule-data', 'MessageSchedulingController@getMessageScheduleData');
        Route::get('message-schedule-data/{id}', 'MessageSchedulingController@messageScheduleData');
        Route::resource('message-scheduling-phone-numbers', 'MessageSchedulePhoneNumberController');
        Route::get('get-message-schedule-contacts/{id}', 'MessageSchedulingController@getMessageSchedulecontacts');
        Route::post('add-contacts-to-schedule', 'MessageSchedulingController@addMessageSchedulecontacts');
        Route::post('detach-contacts-from-schedule', 'MessageSchedulingController@detachMessageScheduleContact');
        Route::get('get-message-schedule-groups/{id}', 'MessageSchedulingController@getMessageScheduleGroups');
        Route::post('add-groups-to-schedule', 'MessageSchedulingController@addMessageScheduleGroups');        
        Route::post('detach-group-from-schedule', 'MessageSchedulingController@detachMessageScheduleGroup');

        // Custom Schedule messages
        Route::resource('custom-message-schedules', 'CustomMessageScheduleController');
        Route::post('change-custom-message-schedule-status/{id}', 'CustomMessageScheduleController@changeCustomScheduleStatus');
        Route::resource('cms-phone-numbers', 'CustomMessageSchedulePhoneNumberController');
        Route::post('detach-custom-contacts-from-schedule', 'CustomMessageScheduleController@detachMessageScheduleContact');
        Route::get('custom-message-schedule-data/{id}', 'CustomMessageScheduleController@customMessageScheduleData');
        Route::post('detach-contacts-custom-schedule', 'CustomMessageScheduleController@detachMessageScheduleContact');
        Route::get('get-custom-schedule-contacts/{id}', 'CustomMessageScheduleController@getMessageSchedulecontacts');
        Route::post('add-custom-contacts-schedule', 'CustomMessageScheduleController@addMessageSchedulecontacts');
        Route::get('get-custom-schedule-groups/{id}', 'CustomMessageScheduleController@getMessageScheduleGroups');
        Route::post('detach-group-from-cms', 'CustomMessageScheduleController@detachMessageScheduleGroup');
        Route::post('add-groups-to-cms', 'CustomMessageScheduleController@addMessageScheduleGroups');    
                        

        // Contacts
        Route::resource('bulk-sms-contacts', 'ContactController');
        Route::post('update-contact', 'ContactController@update');        
        Route::post('update-contact-status/{id}', 'ContactController@updateContactStatus');        
        Route::post('import-contacts', 'ContactController@importContacts');
        //Get contacts (Vue)
        Route::get('get-contacts', 'ContactController@getContacts');
        Route::get('get-contacts/{id}', 'ContactController@getFilteredContacts');
        Route::post('send-message-contact', 'ContactController@sendMessage');        

        // groups
        Route::resource('groups', 'ContactGroupController');
        Route::get('get-group-contacts', 'ContactGroupController@getContacts');
        Route::get('groups/{id}', 'ContactGroupController@getFilteredGroups');
        Route::post('update-group-status/{id}', 'ContactGroupController@updateGroupStatus');
        Route::get('group-members/{id}', 'ContactGroupController@groupMembers');
        Route::post('add-group-members/{id}', 'ContactGroupController@addGroupMembers');
        Route::post('detach-contact', 'ContactGroupController@detachContact');
        Route::put('groups/{id}', 'ContactGroupController@update');
        Route::post('send-group-message', 'ContactGroupController@sendGroupMessage');  
        
        Route::get('get-group-members/{id}', 'ContactGroupController@getGroupMembers');      
        
    });

    // Procurement
    Route::group(['middleware' => ['can:view-procurement']], function () {
        Route::resource('local-purchase-orders', 'LocalPurchaseOrderController');
        Route::get('create-lpo-data', 'LocalPurchaseOrderController@getData');
        Route::resource('lpo-approvers', 'LocalPurchaseOrderApproverController');

        Route::get('get-lpo-data/{id}', 'LocalPurchaseOrderController@getLpoData');
        // LPO Items
        Route::resource('local-purchase-order-items', 'LocalPurchaseOrderItemController');
        Route::post('add-lpo-items', 'LocalPurchaseOrderItemController@addLpoItems');

        Route::get('get-lpo-approvers', 'LocalPurchaseOrderApproverController@getLpoApprovers');
        Route::put('update-lpo-approvers-sequence', 'LocalPurchaseOrderApproverController@updateApproversSequence');

        Route::get('get-lpo-status-logs/{id}', 'LocalPurchaseOrderController@statusLogs');
        Route::post('approve-lpo', 'LocalPurchaseOrderApproverController@approveLpo');
        Route::post('cancel-lpo-approval-request/{id}', 'LocalPurchaseOrderApproverController@cancelApprovalRequest');
        Route::post('send-lpo-approval-request/{id}', 'LocalPurchaseOrderApproverController@sendApprovalRequest');
        
        Route::resource('lpo-statuses', 'LocalPurchaseOrderStatusController');

        Route::resource('set-selling-price', 'SellingPriceController');

        //Download LPO
        Route::get('download-local-purchase-order/{lpo}', 'LocalPurchaseOrderController@downloadLPO')->name('download-local-purchase-order');


        // SRN
        Route::resource('store-requisition-notes', 'StoreRequisitionNoteController');
        Route::get('create-srn-data', 'StoreRequisitionNoteController@getData');
        Route::get('get-available-products/{id}', 'StoreRequisitionNoteController@getAvailableProducts');

        Route::get('get-srn-data/{id}', 'StoreRequisitionNoteController@getSrnData');
        Route::get('get-srn-status-logs/{id}', 'StoreRequisitionNoteController@statusLogs');
        Route::post('approve-srn', 'StoreRequisitionNoteApproverController@approveSrn');
        Route::post('cancel-srn-approval-request/{id}', 'StoreRequisitionNoteApproverController@cancelApprovalRequest');
        Route::post('send-srn-approval-request/{id}', 'StoreRequisitionNoteApproverController@sendApprovalRequest');

        Route::resource('srn-approvers', 'StoreRequisitionNoteApproverController');

        Route::get('get-srn-approvers', 'StoreRequisitionNoteApproverController@getSrnApprovers');
        Route::put('update-srn-approvers-sequence', 'StoreRequisitionNoteApproverController@updateApproversSequence');

        Route::resource('store-requisition-note-items', 'StoreRequisitionNoteItemController');
        Route::post('add-srn-items', 'StoreRequisitionNoteItemController@addSrnItems');
        //Download SRN
        Route::get('download-store-requisition-note/{srn}', 'StoreRequisitionNoteController@downloadSRN')->name('download-store-requisition-note');

        // Good Issue Note
        Route::resource('good-issue-notes', 'GoodIssueNoteController');
        Route::get('download-good-issue-note/{gin}', 'GoodIssueNoteController@downloadGIN')->name('download-good-issue-note');


    });
    
    // Accounts    
    Route::group(['middleware' => ['can:view-accounts']], function () {
        Route::resource('chart-of-accounts', 'ChartOfAccountController')->middleware('can:view-charts-of-account');

        Route::get('get-accounts-data', 'ChartOfAccountController@create');
        Route::get('get-account-categories/{id}', 'ChartOfAccountController@getAccountCategories');
        
        Route::post('add-account-category', 'ChartOfAccountController@addAccountCategory');

        Route::resource('invoices', 'InvoiceController');

        Route::resource('supplier-invoice', 'SupplierInvoiceController');
        Route::get('download-invoice/{invoice}', 'SupplierInvoiceController@downloadInvoice')->name('download-invoice');
        Route::resource('customer-invoice', 'CustomerInvoiceController');

    });

    // users
    Route::group(['middleware' => ['can:view-users']], function () {
        Route::resource('users', 'UserController');
        Route::post('change-user-status/{id}', 'UserController@changeUserAccountStatus')->middleware('can:update-users');
        
    });

    // Roles
    Route::group(['middleware' => ['can:view-roles']], function () {
		Route::resource('roles','RoleController');
        Route::post('copy-role', 'RoleController@copyRole');
        Route::get('update-role/{id}', 'RoleController@update');
	    Route::post('user-roles/attach', 'RoleController@attachUser');
	    Route::post('user-roles/detach', 'RoleController@detachUser');
    });

    // Departments
    Route::group(['middleware' => ['can:view-departments']], function () {
		Route::resource('departments', 'DepartmentController');
		Route::post('change-department-status/{id}', 'DepartmentController@changeDepartmentStatus')->middleware('can:update-department');
	});

    // System settings
    Route::group(['middleware' => ['can:view-settings']], function () {
        Route::resource('system-settings', 'SystemConstantController');

        Route::get('my-account', 'UserController@myAccount')->middleware('password.confirm');

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable, SoftDeletes;

    protected $dates = ['deleted_at'];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'first_name', 
        'last_name', 
        'email', 
        'username', 
        'mobile', 
        'password', 
        'department_id',
        'supervisor_id',
        'status',
        'job_title',
        'avatar_url', 
        'avatar_img',
        'signature_url',
        'key_code',
        'signature'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * [getFullNameAttribute description]
     * @return [type] [string]
     */
    public function getFullNameAttribute()
    {
        return "{$this->first_name} {$this->last_name}";
    }
    
    
    public function getAvatarAttribute()
    {
        return "{$this->avatar_url}{$this->avatar_img}";
    }
   
    public function getUserSignatureAttribute()
    {
        return "{$this->signature_url}/{$this->signature}";
    }

    public function scopeActive($builder)
    {
        return $builder->where('status', true);
    }
    /**
     * [roles description]
     * @return [type] [description]
     */
    public function roles()
    {
        return $this->belongsToMany(
            Role::class,
            'role_user',
            'user_id',
            'role_id'
        );
    }

    /**
     * Checks if User has access to $permissions.
     */
    public function hasAccess(array $permissions) : bool
    {
        // check if the permission is available in any role
        foreach ($this->roles as $role) {
            if($role->hasAccess($permissions)) {
                return true;
            }
        }
        return false;
    }
    
    public function department()
    {
        return $this->belongsTo(Department::class, 'department_id', 'id');
    }

    public function supervisor()
    {     
        return $this->belongsTo(User::class, 'supervisor_id', 'id');   
    }

    public function scopeHasSignature($builder)
    {
        $check = $builder->where('id', auth()->user()->id)->pluck('signature')->first();
        
        if($check != null) return 1; 

        return 0;
    }
}

resources/views/srn/create.blade.php
@extends('layouts.app', ['title' => 'Create SRN'])

@section('content')

     <!-- start page title -->
     <div class="row">
        <div class="col-12">
            <div class="page-title-box">
                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="{{ url('/home') }}">Home</a></li>
                        <li class="breadcrumb-item"><a href="javascript: void(0);">Procurement</a></li>
                        <li class="breadcrumb-item active">SRN</li>
                    </ol>
                </div>
                <h4 class="page-title">Create Store Requisition Note</h4>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-header">
                    <a href="{{ route('store-requisition-notes.index') }}" class="btn btn-success btn-sm" style="border-radius:0px;"><i class="mdi mdi-view-list"></i> S.R.N (s)</a>
                </div>
                <div class="card-body">
                    <create-store-requisition-note></create-store-requisition-note>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/srn/srnpdf.blade.php
<!DOCTYPE html>

<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{{ public_path('assets/css/bootstrap.min.css') }}">
    <title>Store Requisition Note - {{ $data->number }}</title>

    <style>
        @page{
            margin-top: 70px;
        }
        body {
            font-family: "Cambria";
            font-size: 14px;
            background-color: white;
            color: black
        }
        .logo {
            width: 250px;
            max-width: 50%;
            height: 70px;
            float: left;
        }

        .signature {
            width: 100px;
            height: 50px;
        }

        table, tr, td {
            padding: 0px;
            color: black
        }
        .header{
            height: 80px;
        }
        .lpo_number{
            float: right;
            margin-top: 10px;
        }
        .supplier .vendor{
            margin-bottom: 10px;
        }
        .supplier .details {
            width: 100%;
            margin-left: 10px;
        }
        .info{
            margin-top: 5px;
        }
        
        .page_break { page-break-before: always; }
        .no_page_break { page-break-before: avoid; }
        hr{
            color: grey;
            border-bottom: 1px solid grey;
        }
    </style>
</head>
        
    <div class="header">
        <div class="logo">
            <img src="{{ public_path('storage/logo/carrymore_logo.png') }}" height="100%" width="100%">
        </div>
        <div class="lpo_number">
            <p>
                SRN Number:<strong> {{ $data->number }} </strong><br>
                SRN Date: <strong>{{ date('d-m-Y H:i A', strtotime($data->created_at)) }}</strong>
            </p>
        </div>
    </div>
    <hr>
    <div class="row supplier">
        <div class="details">
            <div class="vendor">User Request Info</div>
            <div class="address">
                <address>
                    <strong>{{ $data->user->full_name }}</strong><br>
                    {{ $data->user->department->name }}<br>
                    <abbr title="Phone">Phone:</abbr> {{ $data->user->mobile }}<br>
                    <abbr title="Phone">Email:</abbr> {{ $data->user->email }}
                </address>
            </div>
        </div>
    </div>
    <!-- end row -->

    <div class="info">
        <p>I hereby request the issuance of the following items to replenish the supermarket.</p>
    </div>

    <div>
        <table class="table table-bordered table-condensed table-striped" width="100%">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Item</th>
                    <th>Quantity</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($data->items as $key => $item)
                    <tr>
                        <td>{{ $key+1 }}</td>
                        <td>{{ $item->product->name }}</td>
                        <td>{{ number_format($item->quantity).' '.$item->product->unitOfMeasure->name }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    <div class="col-12" style="page-break-inside: avoid">

        <div class="col-12" style="margin-top: 15px;">
            <table width="100%">
                <tr>
                    <td width="15%"><b>Prepared By:</b></td>
                    <td style="border-bottom: 0.5px solid #000">{{ $prepared_by->full_name }}</td>
                    <td width="8%"><b>Sign:</b></td>
                    <td width="20%" style="border-bottom: 0.5px solid #000" width="20%"><img class="signature" src="{{ public_path('storage/signatures/'.$prepared_by->signature) }}" height="100%" width="100%"></td>
                    <td width="8%"><b>Date:</b></td>
                    <td style="border-bottom: 0.5px solid #000" width="20%">{{ date('d/m/Y', strtotime($data->created_at)) }}</td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                </tr>
                @foreach ($approvers as $approver)
                    <tr>
                        <td>
                            <b>
                                @if(lastApprover($approver->approver->user->id, $data->id) == 0)
                                    Approved By:
                                @else
                                    Authorised By:
                                @endif
                            </b>
                        </td>
                        <td style="border-bottom: 0.5px solid #000">{{ $approver->approver->user->full_name }}</td>
                        <td><b>Sign:</b></td>
                        <td style="border-bottom: 0.5px solid #000">
                            @if($approver->store_requisition_note_status_id == App\StoreRequisitionNoteStatus::APPROVED)
                                <img class="signature" src="{{ public_path('storage/signatures/'.$approver->approver->user->signature) }}" height="100%" width="100%">
                            @endif
                        </td>
                        <td><b>Date:</b></td>
                        <td style="border-bottom: 0.5px solid #000">
                            @if($approver->store_requisition_note_status_id == App\StoreRequisitionNoteStatus::APPROVED)
                                {{ date('d/m/Y', strtotime($data->updated_at)) }}
                            @endif
                        </td>
                    </tr>

                    <tr>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                    </tr>
                @endforeach
                
                
            </table>
        </div>
        
    </div>     